wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.9
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 2
      4: 3.6.9
      5: 0.10.27
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 32
height:
  desc: null
  value: 96
num_epochs:
  desc: null
  value: 100
width:
  desc: null
  value: 96
